### ISSUE TITLE
Does not return most relevant result

### ISSUE THREAD

**Issue by dualmoon** [hubot-scripts/hubot-youtube#1]
In my fork of this I reduced the max-results to 1, which causes it to return only the most relevant result. As it stands, your code returns one of the top 15, or the 15th most relevant result (I'm not sure which). I can see no purpose to increasing the max-results from 1.

**Comment by technicalpickles** [comment]
cc https://github.com/hubot-scripts/hubot-youtube/issues/3

also has some discussions about sometimes it's used intentionally for finding different videos even if the  most relevant isn't exactly what is sought.

**Comment by thomasrussellmurphy** [comment]
Closed by merger of #2.
