### ISSUE TITLE
Get more results than 1

### ISSUE THREAD

**Issue by TheReal1604** [hubot-scripts/hubot-youtube#10]
Hi,

can you embed a env variable to get more results in chat, just than one?

Thx.

Greez
TheReal

**Comment by stephenyeargin** [comment]
There isn't an option to do this right now, but I could see that being an option, sure.

**Comment by TheReal1604** [comment]
This would be really great. I use your script in my docker rocket.chat hubot deployment. So, I can not edit the scripts that easy. The docker application downloads the scripts on startup from npm.. Thanks in advance!
