### ISSUE TITLE
YouTube now returning broken video

### ISSUE THREAD

**Issue by stephenyeargin** [hubot-scripts/hubot-youtube#3]
Reproduction steps:

```
user> hubot yt star wars
hubot> http://www.youtube.com/watch?v=UKY3scPIMd8&feature=youtube_gdata
```

This is a result of an [announced change](https://youtube.com/devicesupport) in their API documentation. The fix will be to switch to an authenticated mode (via OAuth2) to restore functionality. 

---

New endpoint [example](https://developers.google.com/apis-explorer/?hl=en_US#p/youtube/v3/youtube.search.list?part=snippet&q=star+wars&_h=1&):

```
GET https://www.googleapis.com/youtube/v3/search?part=snippet&q=star+wars&key={YOUR_API_KEY}
```

**Comment by stephenyeargin** [comment]
This is actually a lot easier than I thought it was. You can simply go into the [Google API Console](https://console.developers.google.com/) with an authenticated account and obtain a non-auth'd token rather than going through the entire OAuth2 song and dance. As this package does not interact with user data, this is the ideal route.

>Public API access
>Use of this key does not require any user action or consent, does not grant access to any account information, and is not used for authorization. 

![screen_shot_2015-05-12_at_6_08_02_pm](https://cloud.githubusercontent.com/assets/80459/7600553/f2fa44c2-f8d1-11e4-8edf-009c0e3f04f1.png)

**Comment by seanCodes** [comment]
+1, love to see the PR merged and the issue fixed. :grin:

**Comment by stephenyeargin** [comment]
@seanCodes #4 should take care of it. Can you give it a spin? Should be a simple matter of updating your `package.json` file to include:

```json
{
    "hubot-youtube": "git://github.com/stephenyeargin/hubot-youtube.git#bug/3-broken-youtube-search"
}
```

**Comment by Hobbsee** [comment]
@stephenyeargin I tried out your PR - works nicely, thank you!

**Comment by ndaversa** [comment]
I also ran this fork locally and it worked as reported :+1:
