### ISSUE TITLE
6/4 Not returning anything at all

### ISSUE THREAD

**Issue by dylanh724** [hubot-scripts/hubot-youtube#5]
This came default with my bot and returns nothing in hipchat. All other default modules work (except google translate)

**Comment by technicalpickles** [comment]
Sorry for the trouble! This was also reported in https://github.com/hubot-scripts/hubot-youtube/issues/3 so I'm going to close this as a duplicate.

Also: I've updated the hubot generator to not include this since it will require an API key, and google translate was fixed with a new release.
