### ISSUE TITLE
ERROR SyntaxError: Unexpected token N

### ISSUE THREAD

**Issue by jamespullar** [hubot-scripts/hubot-youtube#8]
I just recently updated this script because of the OAuth changes, but I'm now getting this error every time someone tries calling the script. Any ideas?

ERROR SyntaxError: Unexpected token N                                                                    
  at Object.parse (native)
  at /Users/autobots/Desktop/scruffy/node_modules/hubot-youtube/src/youtube.coffee:17:9, <js>:13:23
  at IncomingMessage.<anonymous> (/Users/autobots/Desktop/scruffy/node_modules/hubot/node_modules/scoped-http-client/src/index.js:80:22)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:929:16
  at process._tickCallback (node.js:419:13)

**Comment by stephenyeargin** [comment]
You did go through and add the token environment variable? Seems like either a rate limit message, or some other uncaught exception.

**Comment by edbury** [comment]
I'm getting the same error. Token is set.

**Comment by stephenyeargin** [comment]
@edbury @jamespullar I'm going to add some more debugging information to the script. One other thing to check is that the credential you've added has the `YouTube Data API V3` turned on as well. I have a feeling the error that is coming back is one related to permissions.

**Comment by stephenyeargin** [comment]
An easy way to do this would be to put `https://www.googleapis.com/youtube/v3/search?part=snippet&q=star+wars&key=YOUR_KEY_HERE` into your browser to verify that data is coming through.

**Comment by edbury** [comment]
@stephenyeargin - all of the items seem to be coming back fine if i make a request via the browser

**Comment by stephenyeargin** [comment]
@edbury If you can point your `package.json` for this package to `git://github.com/hubot-scripts/hubot-youtube.git#8-improve-logging` in the version field and add a `HUBOT_LOG_LEVEL=debug`, we may be able to get some more output in the logs than what is currently coming through. I am out of ideas.
